on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - env:
      - name: BLOB_STORAGE_KEY
        value: "DefaultEndpointsProtocol=https;AccountName=parteiblobstorage;AccountKey=LrRrCznOx4SFyeGeBGOW53ndE43LQWN2wFmoIgjA7AobLvECbGVU8iLuoEXXmV8zv+Bl2B3nosGs+RdhZ9hwcQ==;EndpointSuffix=core.windows.net"
      - name: COSMOS_DB_KEY
        value: "LwY1uc8q1gBKskWzATsVaZONh4xBP6WjGQuG5fH4qSGfYJYnHuxBqnF9HyyT8R2Kmm4WWmhk4Sdu80zgKHqPfw=="
    
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: parteicluster.azurecr.io
        username: ${{ secrets.acr_parteicluster_username }}
        password: ${{ secrets.acr_parteicluster_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t parteicluster.azurecr.io/kubernetesparteicluster:${{ github.sha }}
        docker push parteicluster.azurecr.io/kubernetesparteicluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_kubernetesparteicluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep kubernetesparteicluster81f5 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace kubernetesparteicluster81f5`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: kubernetesparteicluster81f5
        container-registry-url: parteicluster.azurecr.io
        container-registry-username: ${{ secrets.acr_parteicluster_username }}
        container-registry-password: ${{ secrets.acr_parteicluster_password }}
        secret-name: kubernetespadockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: kubernetesparteicluster81f5
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          parteicluster.azurecr.io/kubernetesparteicluster:${{ github.sha }}
        imagepullsecrets: |
          kubernetespadockerauth